### ISSUE TITLE
Update PdoConnection to support fetching attributes

### ISSUE THREAD

**Issue by tysonphillips** [phillipsdata/minphp-db#6]
_PdoConnection_ already supports setting an attribute with _PdoConnection::setAttribute_ but it would be useful to also be able to fetch attributes with a method _PdoConnection::getAttribute_ that similarly calls _PDO::getAttribute_. 
See https://secure.php.net/manual/en/pdo.getattribute.php

For example, this will allow us to fetch the current database version with a call to _PDO::getAttribute(PDO::ATTR_SERVER_VERSION)_

**Comment by clphillips** [comment]
Why not use `getConnection()->getAttritubte()`?

Not sure why setAttribute() exists, seems redundant.

**Comment by tysonphillips** [comment]
I suppose `connect()->getAttribute()` would suffice

**Comment by clphillips** [comment]
I guess the only caveat is assuming getConnection() is non-null. 😁
